"""
Centralized constants for the AI Data Engineering Platform.
"""

DASHBOARD_SECTION_LABEL = "Dashboard"
JOB_ALERTS_SECTION_LABEL = "Job Alerts"
CONCEPTS_SECTION_LABEL = "Concepts"
GENAI_SECTION_LABEL = "GenAI"
CODING_SECTION_LABEL = "Coding"
PYTHON_SECTION_LABEL = "Python"
SPARK_SECTION_LABEL = "Spark / Flink"
DATA_MODELING_SECTION_LABEL = "Data Modelling"
ARCHITECTURE_SECTION_LABEL = "Architecture Diagrams"
DEVOPS_SECTION_LABEL = "DevOps"
CLOUD_SECTION_LABEL = "Cloud Platform"
DATA_SOURCES_SECTION_LABEL = "Data Sources & Ingestion"
WAREHOUSES_SECTION_LABEL = "Data Warehouses & Query Engines"
LAKEHOUSE_SECTION_LABEL = "Lakehouse & Table Formats"
ORCHESTRATION_SECTION_LABEL = "Orchestration"
PROJECTS_SECTION_LABEL = "Projects"
ADMIN_SECTION_LABEL = "Admin"

SECTION_ORDER = [
    DASHBOARD_SECTION_LABEL,
    JOB_ALERTS_SECTION_LABEL,
    CONCEPTS_SECTION_LABEL,
    GENAI_SECTION_LABEL,
    CODING_SECTION_LABEL,
    SPARK_SECTION_LABEL,
    DATA_MODELING_SECTION_LABEL,
    DATA_SOURCES_SECTION_LABEL,
    ORCHESTRATION_SECTION_LABEL,
    WAREHOUSES_SECTION_LABEL,
    LAKEHOUSE_SECTION_LABEL,
    ARCHITECTURE_SECTION_LABEL,
    DEVOPS_SECTION_LABEL,
    CLOUD_SECTION_LABEL,
    PROJECTS_SECTION_LABEL,
    ADMIN_SECTION_LABEL,
]

TRACK_KEYS = {
    "sql": "sql",
    "pyspark": "pyspark",
    "python": "python"
}